"""Add additional_data to contacts

Revision ID: 0245aa26ceea
Revises: 3893e7d7d122
Create Date: 2025-04-06 22:58:06.195858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0245aa26ceea'
down_revision: Union[str, None] = '3893e7d7d122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('additional_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'additional_data')
    # ### end Alembic commands ###
